### ISSUE TITLE
Unchecking "Display MyCode formatting options on posting pages" in User CP should disable the editor

### ISSUE THREAD

**Issue by DW01** [samclarke/SCEditor-MyBB#1]
As per title. Currently, unchecking this option in the User CP with SCEditor installed doesn't do anything -- the editor is still there. Maybe replace that checkbox with a drop-down list containing SCEditor, the MyBB default editor and no editor?

**Comment by samclarke** [comment]
I've been looking into implementing this, unfortunately I've yet to work out how to add/change user options in MyBB.

If you happen to know any docs for adding options to the user options or any plugins that modify the users options I would really appreciate it.

**Comment by samclarke** [comment]
Finally worked out how to add this option! It's available in the version 1.4.0.2 from the [downloads page](https://github.com/samclarke/SCEditor-MyBB/downloads).
