### ISSUE TITLE
Emoticon issue

### ISSUE THREAD

**Issue by charafweb** [samclarke/SCEditor-MyBB#14]
Hi Sam,

I deleted the emoticon icon from the toolbar because there is already smileys at the left sidebar (above Your Message: ) and because of some issues with emoticons (please see the snapshot)

![smilies](https://f.cloud.github.com/assets/2504989/40987/b9c68160-55c3-11e2-8d90-97529ca17bc8.png)

but now the editor doesn't render the clicked mybb smilies, please see snapshot:

![smilies2](https://f.cloud.github.com/assets/2504989/40993/2c0105f2-55c4-11e2-9b38-c07d682718b7.png)

Thanks a lot

**Comment by samclarke** [comment]
Currently when you remove `emoticon` from the toolbar it disables all emoticons.

The next version of the editor will have more options for emoticons, like being able to disable/enable them at runtime but currently `emoticon` needs to stay in the toolbar to enable them.

You could add a cludge to remove it temporarily:

```
<style type="text/css">
    .sceditor-button-emoticon { display:none }
</style>
```

I would like to find out why some of the emoticons are not displaying though. The only thing I can think it could be is either another plugin or some non-default setting. Do you have any plugins that might be affecting it?

**Comment by charafweb** [comment]
Thanks for the reply. 

Can't we have just the SCEditor emoticons and  remove the sidebar smilies?

About the not displayed emoticons, it's my fault: I did remove their folder, and I completely forget about it. Sorry.

**Comment by samclarke** [comment]
Just updated to add an option to remove the sidebar emoticons.

**Comment by charafweb** [comment]
Thank you very very much Sam :)
