### ISSUE TITLE
Missing text

### ISSUE THREAD

**Issue by charafweb** [samclarke/SCEditor-MyBB#16]
Hi Sam,

There are missing text here (Please see snapshot)

![disable_side_bar_smilies](https://f.cloud.github.com/assets/2504989/45977/436a1242-580d-11e2-9183-32c395eacc6a.png)

Thanks for your magnificent Editor :)

**Comment by samclarke** [comment]
Whoops, forgot to add the language file to the commit. Should be fixed now.
