### ISSUE TITLE
$page = preg_replace

### ISSUE THREAD

**Issue by martec** [samclarke/SCEditor-MyBB#17]
for me...

this code not work correctly in my forum

$page = preg_replace('/.*?/ism', "", $page);

but code below used in old version work perfectly..

$page = preg_replace('#<script type="text/javascript" src="jscripts/editor.js\?ver=[0-9]{4}"></script>[^<]_<script type="text/javascript">.<!--[^<]_</script>#ism', "", $page);

**Comment by samclarke** [comment]
Thanks for reporting. I've updated it so it should now be a bit more robust at removing the MyCode editor.
