### ISSUE TITLE
Uninstalling issue

### ISSUE THREAD

**Issue by charafweb** [samclarke/SCEditor-MyBB#19]
Hi Sam,

When I uninstalled the editor plugin I had issues with the mybb default editor:

The path to the mybb editor theme is wrong.

![wrong_path](https://f.cloud.github.com/assets/2504989/74225/d7dedade-6082-11e2-9e12-7e9cfdbd7b47.png)

![wrong_path_2](https://f.cloud.github.com/assets/2504989/74226/dd0055e2-6082-11e2-9426-c3e5289b99b0.png)

Thank you

**Comment by charafweb** [comment]
I managed to correct this issue by replacing this: (in jscripts/editor.js)

this.baseURL + 'editor_themes/

by the full path:

http://la-fac.tk/jscripts/editor_themes/

I think that SCEditor has altered the baseURL by some way.

Thanks

**Comment by samclarke** [comment]
It doesn't edit editor.js or touch the base URL in anyway so I can't see how it would have managed that. There's nothing in the [source](https://github.com/samclarke/SCEditor-MyBB/blob/master/inc/plugins/sceditor.php) that should affect that if it's been uninstalled.
