### ISSUE TITLE
Quick Reply PM, and Themes to disable wont work

### ISSUE THREAD

**Issue by Peda1996** [samclarke/SCEditor-MyBB#21]
Quick Reply PM:
It only show the old editor, and the old editor also wont work..

Themes to disable :
I typed in "Mobile-Theme" and it also shown in that Theme, i don't know why

Please help :)

**Comment by samclarke** [comment]
is "Quick Reply PM" a plugin? If so could you provide a link to it so I can make this plugin compatible.

The second problem has now been fixed. It was expecting to be given theme names in lowercase, e.g.:
`mobile-theme`
You can download the fixed version [here](https://github.com/samclarke/SCEditor-MyBB/archive/master.zip).

**Comment by Peda1996** [comment]
That was the plugin :)

http://mods.mybb.com/view/quick-reply-pm

**Comment by Peda1996** [comment]
Now it works, thx
