### ISSUE TITLE
Quote Errors - Going from Editor to Source Mode

### ISSUE THREAD

**Issue by Bhbg** [samclarke/SCEditor-MyBB#28]
The quoting works like it should but it's not using the right methods of doing it in certain circumstances. I am using Euan T's MyAlerts and all of  the alerts there work except for quoted alerts. This is a problem since I am using SCEditor. In source mode when you quote someone, it quotes properly without leaving out the ''s. 

Here's an example:
[quote='test' pid='7718' dateline='1364725904']

TESTING
[/quote]

Now if you go out of source and back to the editor. It changes the quote and leaves out the ''s and you can find that out by going back to source again. It now shows this:

[quote=test pid=7718 dateline=1364725904]

TESTING
[/quote]

Same thing but with the ''s missing from the name, pid and dateline. This usually isn't a problem but since I am using MyAlerts, the quote alerts do not get sent because there are no ''s on the outside of their name. Since the editor removes the ''s from their name, it thinks that it's probably someone else. The ''s were enclosing the name so it was specifically that person which is needed for the MyAlerts to send a quoted message.

Basically, it'll always get rid of the ''s if you are in the editor view and not the source view. This is not helping the MyAlerts quoting at all.

I dug around and experimented a lot, but I have no true way to fix his so I come to you now. I did think of a simple solution if it was possible. I was just thinking that if you could somehow help me or show me how to just always leave it in source mode and get rid of the editor view itself. If it's always in source mode, all the quoting should be fine and all of the tags/codes will still work properly.

My friends will not mind seeing it in source form as in seeing all of the commands like [b][/b] [quote][/quote] and all of that. If I can get a simple fix on to just leave it always on source and remove the editor, I will be satisfied. Thanks in advance!

**Comment by samclarke** [comment]
Thanks for reporting!

I've updated the [quote] BBCode in [version 1 .4.2](https://github.com/samclarke/SCEditor-MyBB/archive/v1.4.2.zip)  so it should now work.
