### ISSUE TITLE
When text is pasted the editor scrolls up.

### ISSUE THREAD

**Issue by maniacmusic** [samclarke/SCEditor-MyBB#37]
Problem can be reproduced by pasting larger text blocks in to the editor.

**Comment by ps915** [comment]
I can confirm the issue. In my forum long tutorials und posts are written. Every time you paste, it jumps to the top.

Similarly, with short text or hyperlinks.
But when using sourcecode view, it doesent appear.

**Comment by derboehsevincent** [comment]
yepp, really anoying bug.

**Comment by derboehsevincent** [comment]
1. Try ;). Really annoying bug, especially handling large text blocks is very frustrating...

**Comment by samclarke** [comment]
Thanks for reporting! This should now be fixed in version 1.4.4 of the plugin which should be released tomorrow or the day after.
