### ISSUE TITLE
Quoting in editor doesn't like usernames with spaces

### ISSUE THREAD

**Issue by DW01** [samclarke/SCEditor-MyBB#4]
I've noticed that every time a name with a space in it comes up in a quote, SCEditor cuts off the name after the space. See this post: http://www.zejroleplaying.org/showthread.php?tid=1081&pid=16764#pid16764

"Lord" should be "Lord X-Giga-X", but SCEditor cuts it off at "Lord" due to the space.

**Comment by samclarke** [comment]
Thanks for reporting! Should now be fixed.
