### ISSUE TITLE
Horizontal scrollbar

### ISSUE THREAD

**Issue by ps915** [samclarke/SCEditor-MyBB#41]
Is it possible to get a horizontal scrollbar when editing Posts?
When there are huge posts oder post with images in there, its not good to view.

**Comment by martec** [comment]
not better use maximize mode?

**Comment by samclarke** [comment]
As @martec says I think maximise is probably the best option.

Unless there was a fixed maximum width you would have to horizontally scroll a lot on large posts and it would also look different when posted so it wouldn't be very WYSIWYG either. As the maximum width depends on the theme and browser viewport, ect. it would be quite tricky to do that and I wouldn't of thought it would be what many people would want either.

If maximise isn't good enough just reopen this and I'll try and think how this could be implemented.
