### ISSUE TITLE
Text area always starts with "^^" in it...?

### ISSUE THREAD

**Issue by Amseog** [samclarke/SCEditor-MyBB#44]
Hello samclarke,

thanks for your great plugin. I would really love to use it in my forum, because it's so much prettier than any other WYSIWYF editor of mybb. But so far it's really broken on my site...

I installed it, following every instruction - but if I click on "New Reply" or "New Thread" and your SCEditor loads, it always has "^^" in the text area, even though I didn't enter any text at all.
The "^^" is then converted to a smiley I attached to that code...
This is what the editor looks like right after loading:
![startposition](https://f.cloud.github.com/assets/5350651/1061503/3a9e8e78-11de-11e3-9a74-0ee1222be1b2.JPG)

More over, everytime I click a smiley from my smilie inserter it will add another "^^"...
![danach](https://f.cloud.github.com/assets/5350651/1061504/3cc272be-11de-11e3-8ab4-444963cdb5d1.JPG)

Maybe you can help me? Thanks in advance!

**Comment by samclarke** [comment]
Thanks for reporting!

I've just added a fix for this, could you check [if this version](https://github.com/samclarke/SCEditor-MyBB/archive/master.zip) solves the issue.

**Comment by Amseog** [comment]
Hey Sam!
Thanks for your very fast reaction!

First: The "^^" bug is gone. The editor now loads clean, and if I add a smiley code there isn't an extra "^^" anymore. Yay!

But.... unfortunately, your fixed version somehow made my smiley inserter invisible?

![gone](https://f.cloud.github.com/assets/5350651/1061607/3951b542-11eb-11e3-8006-ec94ba4a5ef9.JPG)

I just checked the templates, they are still there, but nonetheless the inserter is just gone? Once I deactivate the plugin it's back...

Maybe just another hotfix for this? If this issue is also solved, I will be happily using that great plugin and recommend it to everyone! :)

**Comment by Amseog** [comment]
Never mind.... there seemed to be an issue with the earlier version of my SCE, which didn't uninstall properly.

I deleted all files, uninstalled SCE, installed your fixed SCE - and now everything works like a charm.

Kudos and thanks to you, sam.
