### ISSUE TITLE
Auto detect language and direction

### ISSUE THREAD

**Issue by charafweb** [samclarke/SCEditor-MyBB#5]
Hi,
Can you please make it to auto detect language instead to stick to just a one. For instance if a forum member choose french language for the board SCEditor will be in french, if he choose spanish the editor will be in spanish...and if he choose an rtl language (arabic, farsi, hebrew) the editor will in the rtl direction..
Thank you very much (hope you understand my poor english)

**Comment by samclarke** [comment]
Thanks for the suggestion.

I've updated it to use the users language if it's available and also to use the current languages direction.
