### ISSUE TITLE
SCEditor Not Replacing All TextAreas In MyBB

### ISSUE THREAD

**Issue by gwinston** [samclarke/SCEditor-MyBB#52]
Please make SCEditor replace these text editors:
1. /modcp.php?action=editprofile&uid=1 This is in the ModCP Profile Editor after you have clicked on a user, at the Signature text area, it is still using the default MyBB one.
2. The QuickReply for Guests needs the SCEditor too, right now it's just a blank text area. 

If I find more that need the SCEditor implemented, I'll post here.

**Comment by samclarke** [comment]
Thanks for reporting! This should be fixed in the next version.
